[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "MovieZone Telegram Bot"
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot[job-queue]==20.7",
    "telegram>=0.0.1",
]
